server:
  port: 8080
  servlet:
    context-path: /e-Training
spring:
  application:
    name: duocoding
  datasource:
    url: jdbc:mysql://localhost:3306/duocoding
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:migration
    table: flyway_schema_history
